#!/bin/bash

# AI 設置腳本
echo "🤖 設置 AI 整合功能"
echo "================================"

# 檢查是否存在 .env 文件
if [ ! -f ".env" ]; then
    echo "📝 創建 .env 文件..."
    cp env.example .env
    echo "✅ .env 文件已創建"
else
    echo "✅ .env 文件已存在"
fi

echo ""
echo "🔑 請選擇 AI 提供商並設置 API Key："
echo ""
echo "📋 支持的 AI 提供商："
echo "🆓 免費選項："
echo "1. Groq (最推薦) - 完全免費，超快速度"
echo "2. OpenRouter - 每月 $5 免費額度，多種模型"
echo "3. Hugging Face - 完全免費，開源模型"
echo ""
echo "💰 付費選項："
echo "4. Perplexity AI - 更便宜，支持實時搜索"
echo "5. OpenAI - 功能強大，但較貴"
echo "6. Claude - Anthropic 的 AI 模型"
echo ""
echo "🆓 Groq (免費，推薦) 設置步驟："
echo "1. 前往 Groq Console：https://console.groq.com/"
echo "2. 註冊免費帳戶"
echo "3. 點擊 'Create API Key'"
echo "4. 複製生成的 API Key"
echo "5. 編輯 .env 文件，設置："
echo "   AI_PROVIDER=groq"
echo "   GROQ_API_KEY=您的API_KEY"
echo ""
echo "🆓 OpenRouter (免費額度) 設置步驟："
echo "1. 前往 OpenRouter：https://openrouter.ai/"
echo "2. 註冊帳戶"
echo "3. 前往 API Keys 頁面"
echo "4. 創建新的 API Key"
echo "5. 編輯 .env 文件，設置："
echo "   AI_PROVIDER=openrouter"
echo "   OPENROUTER_API_KEY=您的API_KEY"
echo ""
echo "🔧 快速設置命令："
echo "# Groq (推薦)"
echo "echo 'AI_PROVIDER=groq' >> .env"
echo "echo 'GROQ_API_KEY=您的API_KEY' >> .env"
echo ""
echo "# OpenRouter"
echo "echo 'AI_PROVIDER=openrouter' >> .env"
echo "echo 'OPENROUTER_API_KEY=您的API_KEY' >> .env"
echo ""
echo "📝 .env 文件位置：$(pwd)/.env"
echo ""
echo "⚠️  請確保不要將 API Key 提交到版本控制系統！"
echo ""
echo "🚀 設置完成後，運行以下命令測試 AI 功能："
echo "npm run test:ai"
